package datasource

import (
	"embed"
	"reflect"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"

	"github.com/grafana/thema"
)

const (
	cuePath     = "internal/components/datasource"
	cueFilename = "datasource.cue"
)

var (
	//go:embed datasource.cue
	cueFS embed.FS
)

const (
	schemaName   = "datasource"
	groupName    = "datasource.core.grafana"
	groupVersion = "v1alpha1"
)

var (
	schemaVersion = thema.SV(0, 0)

	// TODO: this should be generated by thema
	schemaOpenapi = apiextensionsv1.JSONSchemaProps{
		Type: "object",
		Properties: map[string]apiextensionsv1.JSONSchemaProps{
			"spec": {
				Type: "object",
				Properties: map[string]apiextensionsv1.JSONSchemaProps{
					"type": {
						Type: "string",
					},
					"typeLogoUrl": {
						Type: "string",
					},
					"access": {
						Type: "string",
					},
					"url": {
						Type: "string",
					},
					"password": {
						Type: "string",
					},
					"user": {
						Type: "string",
					},
					"database": {
						Type: "string",
					},
					"basicAuth": {
						Type: "boolean",
					},
					"basicAuthUser": {
						Type: "string",
					},
					"basicAuthPassword": {
						Type: "string",
					},
					"withCredentials": {
						Type: "boolean",
					},
					"isDefault": {
						Type: "boolean",
					},
					"jsonData": {
						Type: "string",
					},
					"version": {
						Type: "integer",
					},
					"readOnly": {
						Type: "boolean",
					},
				},
			},
		},
	}
)

// ModelSpec
type ModelSpec struct {
	Type              string                 `json:"type"`
	TypeLogoUrl       string                 `json:"typeLogoUrl"`
	Access            string                 `json:"access"`
	Url               string                 `json:"url"`
	Password          string                 `json:"password"`
	User              string                 `json:"user"`
	Database          string                 `json:"database"`
	BasicAuth         bool                   `json:"basicAuth"`
	BasicAuthUser     string                 `json:"basicAuthUser"`
	BasicAuthPassword string                 `json:"basicAuthPassword"`
	WithCredentials   bool                   `json:"withCredentials,omitempty"`
	IsDefault         bool                   `json:"isDefault"`
	JsonData          map[string]interface{} `json:"jsonData,omitempty"`
	Version           int                    `json:"version"`
	ReadOnly          bool                   `json:"readOnly"`
}

// TODO this should be generated by thema
type ModelStatus struct{}

// TODO this should be generated by thema
type ModelObject struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ModelSpec   `json:"spec,omitempty"`
	Status ModelStatus `json:"status,omitempty"`
}

func (in *ModelObject) DeepCopyObject() runtime.Object {
	val := reflect.ValueOf(in).Elem()

	cpy := reflect.New(val.Type())
	cpy.Elem().Set(val)

	ret, ok := cpy.Interface().(runtime.Object)
	if !ok {
		return nil
	}

	return ret
}

// TODO this should be generated by thema
type ModelObjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ModelObject `json:"items"`
}

func (in *ModelObjectList) DeepCopyObject() runtime.Object {
	val := reflect.ValueOf(in).Elem()

	cpy := reflect.New(val.Type())
	cpy.Elem().Set(val)

	ret, ok := cpy.Interface().(runtime.Object)
	if !ok {
		return nil
	}

	return ret
}
